Raise for unseen categories when materializing from an existing `ModelSpec`
Quantco/tabmat pull request #341
Opened 2024-01-24 11:39 UTC by stanmart

Checklist
* [ ] Added a `CHANGELOG.rst` entry

Added a check for unseen levels when materializing a matrix from an existing modelspec. This is analogous to raising an error when trying to predict from categoricals having levels unseen in the training data. This error is especially useful for glum, because it solves [glum PR #748](https://github.com/Quantco/glum/pull/748) when glum with formulas.

It also makes tabmat's formula materialization stricter than formulaic's. The latter only emits a warning in this case, and sets all dummies to zero. I think the proposed tabmat behavior also makes sense, especially in conjunction with glum, but let me know if you think otherwise. (Maybe one point for discussion could be what should happen if `cat_missing_method="zero"`. In the proposed PR, unseen categories still raise a `ValueError`, but a warning plus setting all dummies to zero might also make sense in that case. Same question goes for glum's behavior.)

2024-01-24 19:15 UTC, MatthiasSchmidtblaicherQC requested changes
Thanks! Looks great, just some minor comments.

I am for raising on unseen categories also under `cat_missing_method=="zero"`, i.e. the current proposal. After all, `cat_missing_method` is about missings, so it would be strange if it also governed behavior for other categories. Going with the more restricted version first is also easier because, if we decide to change it later, it won't be a breaking change.

2024-01-25 04:12 UTC, MarcAntoineSchmidtQC approved these changes
Looks good. Thanks @stanmart ! Happy to merge once @MatthiasSchmidtblaicherQC's comments have been addressed.

2024-01-25 09:33 UTC, stanmart commented on src/tabmat/formula.py
> +            unseen_categories = set(data.dropna().unique()) - set(levels)
Yes, exactly. I will perhaps add a short comment about it.

2024-01-25 09:48 UTC, MatthiasSchmidtblaicherQC approved these changes

2024-01-25 10:21 UTC, merged