Fix numpy 2.0 build error
Quantco/tabmat pull request #371
Opened 2024-06-17 13:00 UTC by MarcAntoineSchmidtQC

STILL TESTING

Checklist
* [ ] Added a `CHANGELOG.rst` entry

2024-06-17 15:16 UTC, MarcAntoineSchmidtQC commented
The MacOS job is getting automatically canceled. Not sure what is going on.

2024-06-17 15:31 UTC, MarcAntoineSchmidtQC commented
well... macos-11 has been deprecated and removed...

2024-06-18 07:09 UTC, xhochy requested changes

2024-06-18 07:09 UTC, xhochy commented on pyproject.toml
> +  'numpy',
```suggestion
  'numpy>=1.25',
```

2024-06-18 14:23 UTC, xhochy approved these changes

2024-06-18 14:23 UTC, merged